version: '3'
services:
  playground-web-frontend:
    image: playground-web-frontend:latest
    environment:
      PORT: 3000
    ports:
      - 3000:3000
  playground-web-backend:
    image: playground-web-backend:latest
    ports:
      - 8000:8000